# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-05-05 18:56
from __future__ import unicode_literals

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(help_text=b'This should be an email that does not yet exist on the system.', max_length=254)),
                ('password', models.CharField(default=b'icmo', max_length=255)),
                ('template', models.CharField(choices=[(b'10M', b'$10 Million Company'), (b'4M', b'$4 Million Company')], default=b'10M', max_length=255)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
