# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-05-05 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce_icmo', '0034_auto_20220504_1013'),
        ('salesforce_icmo', '0034_auto_20220504_1053'),
    ]

    operations = [
    ]
