# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-05-05 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revenues', '0001_initial'),
        ('hubspot_icmo', '0001_initial'),
        ('companies', '0002_auto_20220505_2356'),
        ('leads', '0001_initial'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubspotrevenueplansegmentmap',
            name='revenue_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenues.RevenuePlan'),
        ),
        migrations.AddField(
            model_name='hubspotrevenueplansegmentmap',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revenues.Segment'),
        ),
        migrations.AddField(
            model_name='hubspotrevenueplancampaignmonthperformance',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubspot_icmo.HubspotConnection'),
        ),
        migrations.AddField(
            model_name='hubspotrevenueplancampaignmonthperformance',
            name='hubspot_revenue_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubspot_icmo.HubspotRevenuePlan'),
        ),
        migrations.AddField(
            model_name='hubspotrevenueplancampaignmonthperformance',
            name='hubspot_revenue_plan_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubspot_icmo.HubspotRevenuePlanCampaign'),
        ),
        migrations.AddField(
            model_name='hubspotrevenueplancampaignmonthperformance',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenues.Segment'),
        ),
        migrations.AddField(
            model_name='hubspotrevenueplancampaign',
            name='hubspot_revenue_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubspot_icmo.HubspotRevenuePlan'),
        ),
        migrations.AddField(
            model_name='hubspotrevenueplancampaign',
            name='programs',
            field=models.ManyToManyField(to='leads.Program'),
        ),
        migrations.AddField(
            model_name='hubspotrevenueplancampaign',
            name='revenue_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenues.RevenuePlan'),
        ),
        migrations.AddField(
            model_name='hubspotrevenueplan',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_plans', to='hubspot_icmo.HubspotConnection'),
        ),
        migrations.AddField(
            model_name='hubspotrevenueplan',
            name='revenue_plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='revenues.RevenuePlan'),
        ),
        migrations.AddField(
            model_name='hubspotdeal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='hubspotdeal',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='hubspot_icmo.HubspotConnection'),
        ),
        migrations.AddField(
            model_name='hubspotdeal',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubspot_icmo.HubspotContact'),
        ),
        migrations.AddField(
            model_name='hubspotcontactevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='hubspotcontactevent',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hubspot_icmo.HubspotConnection'),
        ),
        migrations.AddField(
            model_name='hubspotcontactevent',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hubspot_icmo.HubspotContact'),
        ),
        migrations.AddField(
            model_name='hubspotcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='hubspotcontact',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='hubspot_icmo.HubspotConnection'),
        ),
        migrations.AddField(
            model_name='hubspotconnection',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='hubspotcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='hubspotcompany',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_companies', to='hubspot_icmo.HubspotConnection'),
        ),
        migrations.AddField(
            model_name='hubspotcampaigntoicmocampaign',
            name='hubspot_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icmo_campaigns', to='hubspot_icmo.HubspotRevenuePlanCampaign'),
        ),
        migrations.AddField(
            model_name='hubspotcampaigntoicmocampaign',
            name='icmo_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_campaigns', to='performance.Campaign'),
        ),
    ]
