# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-05-05 18:56
from __future__ import unicode_literals

import core.fields
import core.models
from decimal import Decimal
import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revenues', '0001_initial'),
        ('budgets', '0002_budgetlineitem_company'),
        ('companies', '0002_auto_20220505_2356'),
        ('leads', '0001_initial'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('period', models.CharField(choices=[(b'jan', b'jan'), (b'feb', b'feb'), (b'mar', b'mar'), (b'apr', b'apr'), (b'may', b'may'), (b'jun', b'jun'), (b'jul', b'jul'), (b'aug', b'aug'), (b'sep', b'sep'), (b'oct', b'oct'), (b'nov', b'nov'), (b'dec', b'dec'), (b'q1', b'q1'), (b'q2', b'q2'), (b'q3', b'q3'), (b'q4', b'q4'), (b'year', b'year')], db_index=True, max_length=10)),
                ('period_type', models.CharField(choices=[(b'month', b'Month'), (b'quarter', b'Quarter'), (b'year', b'Year')], max_length=50)),
                ('resolution', models.CharField(choices=[(b'campaign', b'Campaign'), (b'custom_budget_line_item', b'Custom Budget Line Item'), (b'program', b'Program'), (b'segment', b'Segment'), (b'revenue_plan', b'Revenue Plan'), (b'company', b'Company')], max_length=100)),
                ('budget_plan_currency', djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('budget_actual_currency', djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('budget_plan', core.fields.DefaultMoneyField(decimal_places=0, default=Decimal('0'), default_currency=b'USD', max_digits=13)),
                ('budget_actual', core.fields.DefaultMoneyField(decimal_places=0, default=Decimal('0'), default_currency=b'USD', max_digits=13)),
                ('budget_variance_currency', djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('roi_plan', models.IntegerField(default=0, editable=False)),
                ('budget_variance', core.fields.DefaultMoneyField(decimal_places=0, default=Decimal('0'), default_currency=b'USD', max_digits=13)),
                ('roi_actual', models.IntegerField(default=0, editable=False)),
                ('roi_variance', models.IntegerField(default=0, editable=False)),
                ('contacts_plan', models.IntegerField(default=0)),
                ('mql_plan', models.IntegerField(default=0, verbose_name=b'MQLs Plan')),
                ('sql_plan', models.IntegerField(default=0, verbose_name=b'SQLs Plan')),
                ('sales_plan', models.IntegerField(default=0)),
                ('sales_revenue_plan_currency', djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('sales_revenue_plan', core.fields.DefaultMoneyField(decimal_places=0, default=Decimal('0'), default_currency=b'USD', max_digits=13)),
                ('touches_plan', models.IntegerField(default=0)),
                ('cost_per_mql_plan_currency', djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('cost_per_sql_plan_currency', djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('cost_per_mql_plan', core.fields.DefaultMoneyField(decimal_places=2, default=Decimal('0'), default_currency=b'USD', max_digits=13)),
                ('cost_per_sql_plan', core.fields.DefaultMoneyField(decimal_places=2, default=Decimal('0'), default_currency=b'USD', max_digits=13)),
                ('average_sale_plan_currency', djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('average_sale_plan', core.fields.DefaultMoneyField(decimal_places=2, default=Decimal('0'), default_currency=b'USD', max_digits=13)),
                ('touches_to_mql_conversion_plan', core.fields.PercentField(decimal_places=1, default=0, max_digits=8, verbose_name=b'Touches to MQL Conversion Plan')),
                ('contacts_to_mql_conversion_plan', core.fields.PercentField(decimal_places=1, default=0, max_digits=8, verbose_name=b'Contacts to MQL Conversion Plan')),
                ('mql_to_sql_conversion_plan', core.fields.PercentField(decimal_places=1, default=0, max_digits=8, verbose_name=b'MQL to SQL Conversion Plan')),
                ('sql_to_sale_conversion_plan', core.fields.PercentField(decimal_places=1, default=0, max_digits=8, verbose_name=b'SQL to Sale Conversion Plan')),
                ('touches_per_contact_plan', models.IntegerField(default=0)),
                ('contacts_actual', models.IntegerField(default=0)),
                ('mql_actual', models.IntegerField(default=0, verbose_name=b'MQLs Actual')),
                ('sql_actual', models.IntegerField(default=0, verbose_name=b'SQLs Actual')),
                ('sales_actual', models.IntegerField(default=0)),
                ('sales_revenue_actual_currency', djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('sales_revenue_actual', core.fields.DefaultMoneyField(decimal_places=0, default=Decimal('0'), default_currency=b'USD', max_digits=13)),
                ('touches_actual', models.IntegerField(default=0)),
                ('cost_per_mql_actual_currency', djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('cost_per_sql_actual_currency', djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('cost_per_mql_actual', core.fields.DefaultMoneyField(decimal_places=2, default=Decimal('0'), default_currency=b'USD', max_digits=13)),
                ('average_sale_actual_currency', djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('cost_per_sql_actual', core.fields.DefaultMoneyField(decimal_places=2, default=Decimal('0'), default_currency=b'USD', max_digits=13)),
                ('touches_to_mql_conversion_actual', core.fields.PercentField(decimal_places=1, default=0, max_digits=8, verbose_name=b'Touches to MQL Conversion Actual')),
                ('average_sale_actual', core.fields.DefaultMoneyField(decimal_places=2, default=Decimal('0'), default_currency=b'USD', max_digits=13)),
                ('contacts_to_mql_conversion_actual', core.fields.PercentField(decimal_places=1, default=0, max_digits=8, verbose_name=b'Contacts to MQL Conversion Actual')),
                ('mql_to_sql_conversion_actual', core.fields.PercentField(decimal_places=1, default=0, max_digits=8, verbose_name=b'MQL to SQL Conversion Actual')),
                ('sql_to_sale_conversion_actual', core.fields.PercentField(decimal_places=1, default=0, max_digits=8, verbose_name=b'SQL to Sale Conversion Actual')),
                ('touches_per_contact_actual', models.IntegerField(default=0)),
                ('contacts_variance', models.IntegerField(default=0)),
                ('mql_variance', models.IntegerField(default=0, verbose_name=b'MQLs Variance')),
                ('sql_variance', models.IntegerField(default=0, verbose_name=b'SQLs Variance')),
                ('sales_variance', models.IntegerField(default=0)),
                ('sales_revenue_variance_currency', djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('touches_variance', models.IntegerField(default=0)),
                ('sales_revenue_variance', core.fields.DefaultMoneyField(decimal_places=0, default=Decimal('0'), default_currency=b'USD', max_digits=13)),
                ('cost_per_mql_variance_currency', djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('cost_per_sql_variance_currency', djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('cost_per_mql_variance', core.fields.DefaultMoneyField(decimal_places=2, default=Decimal('0'), default_currency=b'USD', max_digits=13)),
                ('average_sale_variance_currency', djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar')], default=b'USD', editable=False, max_length=3)),
                ('cost_per_sql_variance', core.fields.DefaultMoneyField(decimal_places=2, default=Decimal('0'), default_currency=b'USD', max_digits=13)),
                ('touches_to_mql_conversion_variance', core.fields.PercentField(decimal_places=1, default=0, max_digits=8, verbose_name=b'Touches to MQL Conversion Variance')),
                ('average_sale_variance', core.fields.DefaultMoneyField(decimal_places=2, default=Decimal('0'), default_currency=b'USD', max_digits=13)),
                ('contacts_to_mql_conversion_variance', core.fields.PercentField(decimal_places=1, default=0, max_digits=8, verbose_name=b'Contacts to MQL Conversion Variance')),
                ('mql_to_sql_conversion_variance', core.fields.PercentField(decimal_places=1, default=0, max_digits=8, verbose_name=b'MQL to SQL Conversion Variance')),
                ('sql_to_sale_conversion_variance', core.fields.PercentField(decimal_places=1, default=0, max_digits=8, verbose_name=b'SQL to Sale Conversion Variance')),
                ('touches_per_contact_variance', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.Campaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('custom_budget_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='budgets.BudgetLineItem')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.Program')),
                ('revenue_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revenues.RevenuePlan')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revenues.Segment')),
            ],
            options={
                'ordering': ('order',),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.models.DenormalizedIcmoParentsMixin, models.Model),
        ),
    ]
