# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-05-04 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20151204_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwaitingPaypalAuthorization',
        ),
        migrations.RemoveField(
            model_name='paypalcouponregistry',
            name='icmo_coupon',
        ),
        migrations.DeleteModel(
            name='PaypalNotification',
        ),
        migrations.RemoveField(
            model_name='paypalsubscriptionplanregistry',
            name='icmo_coupon',
        ),
        migrations.RemoveField(
            model_name='paypalsubscriptionplanregistry',
            name='icmo_plan',
        ),
        migrations.RemoveField(
            model_name='paypalsubscriptionplanregistry',
            name='variant_of',
        ),
        migrations.RemoveField(
            model_name='paypalsubscriptionregistry',
            name='icmo_subscription',
        ),
        migrations.RemoveField(
            model_name='stripecouponregistry',
            name='icmo_coupon',
        ),
        migrations.RemoveField(
            model_name='stripesubscriptionplanregistry',
            name='icmo_plan',
        ),
        migrations.RemoveField(
            model_name='stripesubscriptionregistry',
            name='icmo_subscription',
        ),
        migrations.DeleteModel(
            name='PaypalCouponRegistry',
        ),
        migrations.DeleteModel(
            name='PaypalSubscriptionPlanRegistry',
        ),
        migrations.DeleteModel(
            name='PaypalSubscriptionRegistry',
        ),
        migrations.DeleteModel(
            name='StripeCouponRegistry',
        ),
        migrations.DeleteModel(
            name='StripeSubscriptionPlanRegistry',
        ),
        migrations.DeleteModel(
            name='StripeSubscriptionRegistry',
        ),
    ]
